#!/bin/sh
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 1 "key +ctrl +z -z -ctrl"
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 2 "key e" # toggle eraser mode
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 3 "key b" # brush tool
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 8 "key +shift +ctrl = -ctrl -shift"
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 9 "key +ctrl - -ctrl"
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 10 "key +ctrl d -ctrl"
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 11 "key shift" # hold shift and move cursor to change brush size
xsetwacom --set 'HUION Huion Tablet Pad pad' Button 12 "key +ctrl p -ctrl" # changed the keybind, to be able to change to pan tool

# # The below value was gathered using xrandr and xinput to determine the monitor as well as which
# # number the HUION PenTablet Pen stylus device **id** listed as.
# #    ↳ HUION PenTablet Pen stylus                 id=15   [slave  pointer  (2)]
# #stylus=$(xinput --list --short | grep HUION | grep stylus | awk '{ print $8 }' | grep -o -E '[0-9]+') # this uses awk
# stylus=$(xinput --list --short | grep HUION | grep stylus | grep -oE 'id=[0-9]+' | grep -oE '[0-9]+' ) # this uses grep, which might be better, since I don't need to count how many columns are before it.
# xinput map-to-output $stylus HDMI-1


# Left handed stylus
#xsetwacom set 'HUION PenTablet Pen stylus' rotate half
